# Generated by Django 4.2.2 on 2023-12-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_newsstory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='preview',
            field=models.CharField(default='Click to Read', max_length=300),
        ),
    ]
